[package]
name = "stegos_valueshuffle"
version = "0.1.0"
edition = "2018"
authors = ["Stegos AG <info@stegos.cc>"]

[dependencies]
hex = "0.3"
lazy_static = "1.1"
parking_lot = "0.6"
rand = "0.6"
rust-crypto = "0.2"
rust-gmp = "0.5"
rust-libpbc = { git = "https://github.com/stegos/rust-pbcintf.git" }
sha3 = "0.8"
log = "0.4"
failure = "0.1"
protobuf = "2.2"
stegos_serialization = {path = "../serialization"}
bitvector = "0.1"
rayon = "1.0"
stegos_crypto = { path = "../crypto" }

