[general]
chain = "dev"
prometheus_endpoint = "127.0.0.1:9893"
api_endpoint = "127.0.0.1:3147"
data_dir = "dev/node03"
consistency_check = "full"

[network]
endpoint = "127.0.0.1:10057"
advertised_endpoint = "127.0.0.1:10057"
handshake_puzzle_difficulty = 100
readiness_threshold = 0
seed_nodes = [
]