[general]
chain = "dev"
prometheus_endpoint = "127.0.0.1:9894"
api_endpoint = "127.0.0.1:3148"
data_dir = "dev/node04"
consistency_check = "full"

[network]
endpoint = "127.0.0.1:10058"
advertised_endpoint = "127.0.0.1:10058"
handshake_puzzle_difficulty = 100
seed_nodes = [
    "127.0.0.1:10055",
    "127.0.0.1:10056",
    "127.0.0.1:10057",
]
